version: "3.8"

services:
  localstack:
    container_name: "mylocalstack"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                
      - "127.0.0.1:53:53/udp"            
      - "127.0.0.1:443:443"             
      - "127.0.0.1:4510-4559:4510-4559"  
      - "127.0.0.1:4566:4566"            
    environment:
      - SERVICES=s3,dynamodb,lambda,apigateway,cloudformation,cloudwatch,sts,iam,events,cognito,ses
      - DEBUG=1
      - DATA_DIR={Dir Path to store data}
      - LAMBDA_EXECUTOR=docker 
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
